const data = [
  {
    taskId: "1",
    poNumber: "41000547",
    plantName: "Another Plant",
    companyName: "Another Company",
    receivedDate: "18-01-2024",
    vendorCode: "789012",
    vendorName: "XYZ Inc.",
    invoiceNumber: "XYZ456",
    invoiceDate: "20-01-2024",
    invoiceAmount: "12,500",
  },
  {
    taskId: "2",
    poNumber: "",
    plantName: "",
    companyName: "",
    receivedDate: "09-02-2024",
    vendorCode: "",
    vendorName: "",
    invoiceNumber: "",
    invoiceDate: "",
    invoiceAmount: "",
  },
  {
    taskId: "3",
    poNumber: "41000550",
    plantName: "Plant 123",
    companyName: "Company 456",
    receivedDate: "10-04-2024",
    vendorCode: "567890",
    vendorName: "PQR Ltd.",
    invoiceNumber: "PQR777",
    invoiceDate: "12-04-2024",
    invoiceAmount: "10,800",
  },
  {
    taskId: "4",
    poNumber: "",
    plantName: "",
    companyName: "",
    receivedDate: "18-01-2024",
    vendorCode: "",
    vendorName: "",
    invoiceNumber: "",
    invoiceDate: "",
    invoiceAmount: "",
  },
  {
    taskId: "5",
    poNumber: "",
    plantName: "",
    companyName: "",
    receivedDate: "20-02-2024",
    vendorCode: "",
    vendorName: "",
    invoiceNumber: "",
    invoiceDate: "",
    invoiceAmount: "",
  },
];

export default data;
